<section class="mt-3 card card-body">
    <h1>Gerenciar Alunos</h1>

    <div class="mt-2">
        <a href="/alunos/novo" class="btn btn-ouline-dark">Novo Aluno</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <th>ID</th>
            <th>Nome</th>
            <th>Matrícula</th>
            <th>CPF</th>
            <th>Email</th>
            <th>Ações</th>
        </thead>

        <tbody>
            <?php
            foreach($alunos as $aluno) {
                echo "
                    <tr>
                        <td>{$aluno->id}</td>
                        <td>{$aluno->nome}</td>
                    </tr>
                ";
            }
            ?>
        </tbody>
    </table>
</section>