<section class="mt-3 card card-body">
    <h1>Gerenciar Professores</h1>

    <div class="mt-2">
        <a href="/professores/novo" class="btn btn-ouline-dark">Novo Professor</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <th>ID</th>
            <th>Nome</th>
            <th>CPF</th>
            <th>Endereço</th>
            <th>Status</th>
            <th>Formação</th>
            <th>Ações</th>
        </thead>

        <tbody>
            <?php
            if (isset($professores) && sizeof($professores) > 0) 
            {
                foreach($professores as $professor) {
                    echo "
                        <tr>
                            <td>{$professor->id}</td>
                            <td>{$professor->nome}</td>
                            <td>{$professor->cpf}</td>
                            <td>{$professor->endereco}</td>
                            <td>{$professor->status}</td>
                            <td>{$professor->formacao}</td>
                            <td>
                                <a href='/professores/editar?id={$professore->$id}' class='btn btn-warning'>Editar</a>
                                <a href='/professores/excluir?id={$professor->$id}' class='btn btn-danger'>Excluir</a>
                            </td>
                            
                        </tr>
                    ";
                }

            }
            ?>
        </tbody>
    </table>
</section>